PRIORITY_LEVEL_LOW = "Low"
PRIORITY_LEVEL_MEDIUM = "Medium"
PRIORITY_LEVEL_HIGH = "High"

PRIORITY_CHOICES = [
    (PRIORITY_LEVEL_HIGH, PRIORITY_LEVEL_HIGH),
    (PRIORITY_LEVEL_MEDIUM, PRIORITY_LEVEL_MEDIUM),
    (PRIORITY_LEVEL_LOW, PRIORITY_LEVEL_LOW),
]

ROLE_MENTOR = "Mentor"
ROLE_TRAINEE = "Trainee"

ROLE_CHOICES = [
    (ROLE_MENTOR, ROLE_MENTOR),
    (ROLE_TRAINEE, ROLE_TRAINEE),
]