PRIORITY_LEVEL_LOW = "Low"
PRIORITY_LEVEL_MEDIUM = "Medium"
PRIORITY_LEVEL_HIGH = "High"

PRIORITY_CHOICES = [
    (PRIORITY_LEVEL_HIGH, PRIORITY_LEVEL_HIGH),
    (PRIORITY_LEVEL_MEDIUM, PRIORITY_LEVEL_MEDIUM),
    (PRIORITY_LEVEL_LOW, PRIORITY_LEVEL_LOW),
]