# Generated by Django 4.2.4 on 2023-08-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0002_remove_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("Mentor", "Mentor"), ("Trainee", "Trainee")],
                default="Trainee",
                max_length=255,
            ),
        ),
    ]
